### ISSUE TITLE
Problem with build.gradle

### ISSUE THREAD

**Issue by miguelramosfdz** [oscarcpozas/cooking-app-flutter#2]
There is an error running android app using Android Studio.

I've solved with my current **build.gradle**:
`buildscript {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
    }
}

allprojects {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

**Comment by oscarcpozas** [comment]
Oh thank you for reporting, I'll check it out.

**Comment by oscarcpozas** [comment]
Resolved on latest commit: ced1e40db55a63f3ff387ae1491641346a569323
